### ISSUE TITLE
Bug - `CKEDITOR is not defined` when CKEDITOR is disabled and window too small when loading Text Template.

### ISSUE THREAD

**Issue by VeldoraTheDragon** [znuny/Znuny#609]
### Environment

- Server OS: FreeBSD 13.3
- Browser: Brave 1.70.119
- Znuny version: 6.5.6

### Expected behavior

When loading a Text Template in the `Communication -> Note` while the RichTextEditor is disabled and the screen is extremly small, the template should still load, without even bothering, if `CKEDITOR` is disabled or not.

### Actual behavior

When loading a Text Template in the `Communication -> Note` while the RichTextEditor is disabled and the screen is extremely small, the TextArea doesn't update and the loading-circle is circling forever, saying in the browser-console, that `CKEDITOR` is not defined.
```
CommonJS_1fb76dcb19b7ee7c1c67869ef1461b2b.js:1648 Uncaught ReferenceError: CKEDITOR is not defined
    at UpdateTextarea (CommonJS_1fb76dcb19b7ee7c1c67869ef1461b2b.js:1648:377)
    at String.<anonymous> (CommonJS_1fb76dcb19b7ee7c1c67869ef1461b2b.js:1662:29)
    at Function.each (CommonJS_1fb76dcb19b7ee7c1c67869ef1461b2b.js:1:3179)
    at UpdateFormElements (CommonJS_1fb76dcb19b7ee7c1c67869ef1461b2b.js:1657:3)
    at Object.success (CommonJS_1fb76dcb19b7ee7c1c67869ef1461b2b.js:1674:6)
    at c (CommonJS_1fb76dcb19b7ee7c1c67869ef1461b2b.js:1:25266)
    at Object.fireWith [as resolveWith] (CommonJS_1fb76dcb19b7ee7c1c67869ef1461b2b.js:1:26015)
    at l (CommonJS_1fb76dcb19b7ee7c1c67869ef1461b2b.js:1:77721)
    at XMLHttpRequest.<anonymous> (CommonJS_1fb76dcb19b7ee7c1c67869ef1461b2b.js:1:80204)
```

I've pinned down the relevant code that's causing the issue.
https://github.com/znuny/Znuny/blob/c2b68ffafb3d5fec650222b7c4cfebde69312717/var/httpd/htdocs/js/Core.AJAX.js#L265-L267

Is there a way to somehow implement a check, if `CKEDITOR` is defined, instead of assuming that it isn't disabled?
I guess this would already bypass the issue.

### How to reproduce

1. Disable the RichTextEditor
2. Open a Queue with asigned Text Templates
3. Open a Ticket in this Queue
4. Open `Communication -> Note`
5. Resize the pop-up window to very small
6. Load the Text-Template
7. See error in browser-console.

**Comment by dignin** [comment]
Internal Issue: 1187

**Comment by dennykorsukewitz** [comment]
This issue is only relevant for 6.5.
See changes. in 7.2.

**Comment by dennykorsukewitz** [comment]
Fixed in 6.5.16 via 6a3a6c54dc1acf5eaea2bfd26db35b5c12c5e030
